body:
  - type: markdown
    attributes:
      value: |
        ### Please read the following:
        Thanks for taking the time to open a discussion!

        Please make sure that you're using the correct discussion category:
         - If you have a question, please [use the "Q&A" category](https://github.com/sircharlo/meeting-media-manager/discussions/new?category=q-a). 
         - If you have an idea or suggestion, please [use the "Ideas" category](https://github.com/sircharlo/meeting-media-manager/discussions/new?category=ideas). 
         - If you have a problem, please [create an issue](https://github.com/sircharlo/meeting-media-manager/issues/new/choose).

        If you want to discuss something else, you're in the right place! Please fill out the fields below.
  - type: textarea
    id: discussion
    attributes:
      label: What do you want to discuss?
      description: Show appreciation, share something interesting or talk about anything else.
    validations:
      required: true
