name: Build

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint files
        run: |
          yarn lint
          yarn type-check
      - name: Build and Publish Electron App
        run: |
          yarn icons
          yarn build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: M³ test build for ${{ matrix.os == 'macos-13' && 'Intel-based macOS' || matrix.os == 'macos-latest' && 'M-series (Apple Silicon) macOS' || matrix.os == 'windows-latest' && 'Windows' || 'Linux' }}
          path: |
            dist/electron/Packaged/*.exe
            dist/electron/Packaged/*.dmg
            dist/electron/Packaged/*.zip
            dist/electron/Packaged/*.AppImage
            dist/electron/Packaged/*/*/Contents/Info.plist
