name: Test

on:
  workflow_call:
    inputs:
      checkout-latest:
        description: 'Checkout the latest changes from the repository'
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        if: ${{ inputs.checkout-latest == true }}
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Check out Git repository
        if: ${{ inputs.checkout-latest == false }}
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint files
        run: |
          yarn quasar prepare
          yarn lint
          yarn type-check
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        if: ${{ inputs.checkout-latest == true }}
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Check out Git repository
        if: ${{ inputs.checkout-latest == false }}
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: |
          yarn quasar prepare
          yarn test:unit:ci
